[package]
name = "tsl_api"
version = "2.0.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.12.1"
derive_more = "2.1.1"
env_logger = "0.11.9"
hex = "0.4.3"
hmac = "0.12.1"
log = "0.4.29"
r2d2 = "0.8.10"
rusqlite = "0.38.0"
serde_json = "1.0.149"
sha2 = "0.10.9"
tokio = "1.49.0"
